<?php
/**
 * Created by PhpStorm.
 * User: 65100
 * Date: 2018/12/5
 * Time: 9:37
 */

namespace app\admin\controller;

use think\Controller;
use think\facade\Session;
use think\facade\Request;
use think\Image;

class Base extends Controller
{
    // 初始化方法
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    // 检测管理员是否登录
    public function isAdminLogined()
    {
        if (!Session::get('admin_id')) {
            $this->error('请先登录', 'user/goLoginPage');
        }
    }

    // 图片上传
    public function upload()
    {
        $images = []; // 保存图片在服务器上的地址
        $errors = []; // 保存错误信息
        $files= Request::file();

        foreach ($files as $file) {
            $info = $file->move('uploads/');
            $image = Image::open('uploads/'.$info->getSaveName());
            $image->thumb(400, 300)->save('uploads/'.$info->getSaveName());
            if($info){
                $path = '/uploads/'.$info->getSaveName();
                array_push($images, $path);
            }else{
                array_push($errors, $file->getError());
            }
        }

        if (0 == count($errors)) {
            $msg['errno'] = 0;
            $msg['data'] = $images;
            return json($msg);
        } else {
            $msg['errno'] = 1;
            $msg['data'] = $images;
            return json($msg);
        }
    }

    // 删除图片
}