<?php
/**
 * Created by PhpStorm.
 * User: 65100
 * Date: 2018/12/5
 * Time: 9:37
 */

namespace app\index\controller;

use think\Controller;

class Base extends Controller
{
    // 初始化方法
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}