<?php
/**
 * Created by PhpStorm.
 * User: 65100
 * Date: 2019/3/18
 * Time: 8:57
 */

namespace app\api\controller;

use think\Controller;

class Base extends Controller
{
    /**
     * 初始化方法
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}